### ISSUE TITLE
Might should not use jQuery's trigger() in testing

### ISSUE THREAD

**Issue by zhenya-zhu** [infinum/learnQuery#6]
I finished on() and off(), failed with test 3, 5, 6
And I found two repos on github which finished on and off , they failed with these testings too. [repo1](https://github.com/Svarcf/learnQuery-master) [reop2](https://github.com/derickruiz/learnquery)
Then I found issue #2 also mentioned jQuery's trigger() have some extra work.
We use our on and off, then use jQuery's trigger and Jasmine's spy function to test, there might have some bugs, I guess.

Did you have pass all testing? If yes, could you share the code?
And this is my [repo](https://github.com/EzioKissshot/LearnQuery), if you can pointout where are the bugs, very thanks.

And I will finish my trigger() and replace jQuery's, to see if this is the point.

**Comment by andreicek** [comment]
Thanks for the report and you are correct - `trigger()` from jQuery should not be used in tests. I'll remove it.

**Comment by andreicek** [comment]
Can you please check now?

Thanks! 😸

**Comment by zhenya-zhu** [comment]
@andreicek All passed, good job! Thank you!
